name: CD

on:
  release:
    types: [released, prereleased]

permissions:
  contents: read
  id-token: write # Required to authenticate with npm
  # Required for the docs deployment job
  actions: read
  pages: write

jobs:
  docs:
    uses: ./.github/workflows/docs.yml
    secrets: inherit
    with:
      deploy: true

  publish:
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build --workspaces --if-present
      - run: npm publish --workspaces
        if: "!github.event.release.prerelease"
      # npm requires explicitly specifying a "tag" like `next` if the semantic version is a prerelease like `2.0.0-alpha1`
      - run: npm publish --workspaces --tag next
        if: github.event.release.prerelease
