name: CI

on:
  pull_request:
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ${{ matrix.ros_distro }} (node ${{ matrix.node_version }})
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.ros_distro }}-ros-core
      options: --cap-add=SYS_ADMIN
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [noetic]
        node_version: [20, 22, 24]
    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{ matrix.node_version }}
      - name: Install apt dependencies
        run: |
          apt-get install -q -y libasound2 libnss3 ros-$ROS_DISTRO-rosbridge-server ros-$ROS_DISTRO-tf2-web-republisher ros-$ROS_DISTRO-common-tutorials ros-$ROS_DISTRO-rospy-tutorials ros-$ROS_DISTRO-actionlib-tutorials
      - name: Tests
        run: |
          bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && bash test/build.bash"
